### ISSUE TITLE
Same alternative text

### ISSUE THREAD

**Issue by elinasohn** [gkerber/gkerber.github.io#1]
**1. Page title:** 

I Have A Havanese

**2. Filename:** 

index.html
history.html
characteristics.html
health.html
contact.html

**3. URL**

[https://gkerber.github.io/website/index.html](https://gkerber.github.io/website/index.html)
[https://gkerber.github.io/website/history.html](https://gkerber.github.io/website/history.html)
[https://gkerber.github.io/website/characteristics.html](https://gkerber.github.io/website/characteristics.html)
[https://gkerber.github.io/website/health.html](https://gkerber.github.io/website/health.html)
[https://gkerber.github.io/website/contact.html](https://gkerber.github.io/website/contact.html
)

**4. Type of issue:**

Accessibility

**5. Description of issue**

A nearby image has the same alternative text.  The image of the paw prints has the alternative text with “Havanese clip art” and clipart transparent.png also has the same alternative text. I would suggest changing the alt differently.

**Comment by gkerber** [comment]
Done!  Great catch.
